#
# Module manifest for module 'esxcustomizer'
#
# Generated by: Chrissy LeMaire & Joseph Warren
#
# Generated on: 4/8/2019
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule         = 'esxcustomizer.psm1'

    # Version number of this module.
    ModuleVersion      = '2.8.1'

    # ID used to uniquely identify this module
    GUID               = '50d053b6-650c-48e6-8d8a-dcf01f640d99'

    # Author of this module
    Author             = 'Andreas Peetz'

    # Company or vendor of this module
    CompanyName        = ''

    # Copyright statement for this module
    Copyright          = 'Copyright (c) 2020, licensed under GPL'

    # Description of the functionality provided by this module
    Description        = "A module to build a customized ESXi installation ISO using ImageBuilder"

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion  = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules    = @('PSFramework', 'PoshRSJob')

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess   = @()

    # Functions to export from this module
    FunctionsToExport  = @(

    )

    # Cmdlets to export from this module
    CmdletsToExport    = @()

    # Variables to export from this module
    VariablesToExport  = @()

    # Aliases to export from this module
    AliasesToExport    = @()

    PrivateData        = @{
        # PSData is module packaging and gallery metadata embedded in PrivateData
        # It's for rebuilding PowerShellGet (and PoshCode) NuGet-style packages
        # We had to do this because it's the only place we're allowed to extend the manifest
        # https://connect.microsoft.com/PowerShell/feedback/details/421837
        PSData = @{
            # The primary categorization of this module (from the TechNet Gallery tech tree).
            Category     = "Operating System"

            # Keyword tags to help users find this module via navigations and search.
            Tags         = @('esx', 'iso')

            # The web address of an icon which can be used in galleries to represent this module
            IconUri      = "https://1.bp.blogspot.com/-B1KOrwysPfI/Uo5eh1d-_nI/AAAAAAAABOI/kk_9FO2CfeE/s1600/ESXi-Customizer-PS-trans.png"

            # The web address of this module's project or support homepage.
            ProjectUri   = "https://github.com/potatoqualitee/acas"

            # The web address of this module's license. Points to a page that's embeddable and linkable.
            LicenseUri   = "https://opensource.org/licenses/MIT"

            # Release notes for this particular version of the module
            ReleaseNotes = ""

            # If true, the LicenseUrl points to an end-user license (not just a source license) which requires the user agreement before use.
            # RequireLicenseAcceptance = ""

            # Indicates this is a pre-release/testing version of the module.
            IsPrerelease = 'True'
        }
    }
}

